### ISSUE TITLE
Add TaskLauncherCFSink

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-stream-app-starters#224] opened 2016-09-16 14:41 UTC
As a developer, I'd like to add TaskLauncherCFSink, so we can use this application to consume Task events and launch a Task using the CF deployer.

Acceptance:
I can launch a task by a stream that's running in cf platform.

**Comment by sabbyanandan** [comment] 2016-09-16 14:46
Duplicate of https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/196.

**Closed by sabbyanandan** 2016-09-16 14:46 UTC
